server:
  port: 8080
  servlet.context-path: /esia_debug


esia:
  environment: test
  scopes: fullname, birthdate, gender, snils, id_doc, email, mobile

  #file path to ESIA public certificate for JWT verification
  certificate-path: ${ESIA_CERTIFICATE_PATH}

  connect-timeout: 1m
  read-timeout: 1m


  client-id: ${ESIA_CLIENT_ID}
  #  client-certificate-hash: AAABBBCCC
  #  return-url: http://localhost:${server.port}${server.servlet.context-path}/login/oauth2/code/esia
  return-url: http://localhost:${server.port}${server.servlet.context-path}/login/oauth2/code/esia_debug

  keystore-alias: ${ESIA_KEYSTORE_ALIAS}
  keystore-password: ${ESIA_KEYSTORE_PASSWORD}

  #  cabinet-redirect-url: http://127.0.0.1:7101/CabinetMain-CabinetViewController-context-root/token_auth_callback
  cabinet-redirect-url: http://wl3n3.miit.ru:7003/cabinet/token_auth_callback



spring:
  datasource:
    url: ${esia.db.url:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=${esia.db.host:db2.miit.ru})(PORT=${esia.db.port:1521})))(CONNECT_DATA=(SERVICE_NAME=${esia.db.name:cgeneral.miit.ru})))}
    username: ${esia.db.username:wlapp_u2_my}
    password: ${esia.db.password}
    driver-class-name: oracle.jdbc.OracleDriver

logging.level:
  ru.unisuite.identity: DEBUG
  org.springframework:
    web.client.RestTemplate: DEBUG
