server.port: 8080

esia:
  auth-code-url: https://esia-portal1.test.gosuslugi.ru/aas/oauth2/ac
  access-token-url: https://esia-portal1.test.gosuslugi.ru/aas/oauth2/te
  client-id: ${ESIA_CLIENT_ID}
  return-url: http://localhost:${server.port}/esia_return

  keystore-alias: ${ESIA_KEYSTORE_ALIAS}
  keystore-password: ${ESIA_PRIVATE_KEY_PASSWORD}



logging.level:
  cyclone: DEBUG
