server.port: 8080

esia:
  base-url: https://esia-portal1.test.gosuslugi.ru
  #  base-url: https://esia.gosuslugi.ru
  auth-code-url: ${esia.base-url}/aas/oauth2/ac
  access-token-url: ${esia.base-url}/aas/oauth2/te
  data-collections-url: ${esia.base-url}/rs/prns

  issuer: http://esia-portal1.test.gosuslugi.ru/
  #file path to ESIA public certificate for JWT verification
  certificate-path: ${ESIA_CERTIFICATE_PATH}

  connect-timeout: 30s
  read-timeout: 30s


  client-id: ${ESIA_CLIENT_ID}
  return-url: http://localhost:${server.port}/login/oauth2/code/esia

  keystore-alias: ${ESIA_KEYSTORE_ALIAS}
  keystore-password: ${ESIA_KEYSTORE_PASSWORD}

  cabinet-redirect-url: http://127.0.0.1:7101/CabinetMain-CabinetViewController-context-root/token_auth_callback



spring:
  datasource:
    url: ${esia.db.url:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=${esia.db.host:db2.miit.ru})(PORT=${esia.db.port:1521})))(CONNECT_DATA=(SERVICE_NAME=${esia.db.name:cgeneral.miit.ru})))}
    username: ${esia.db.username:wlapp_u2_my}
    password: ${esia.db.password}
    driver-class-name: oracle.jdbc.OracleDriver

logging.level:
  ru.unisuite.identity: DEBUG
