server:
  port: 8080
  servlet.context-path: /authprovider


esia:
  environment: test
  certificate-path: ${ESIA_CERTIFICATE_PATH}

  scopes: fullname, birthdate, gender, snils, id_doc, email, mobile

  base-url: http://localhost:59185/authprovider

  connect-timeout: 1m
  read-timeout: 1m


  client-id: ${ESIA_CLIENT_ID}
  #  client-certificate-hash: AAABBBCCC

  keystore-alias: ${ESIA_KEYSTORE_ALIAS}
  keystore-password: ${ESIA_KEYSTORE_PASSWORD}

  client:
    registration:
      cabinet:
        #        redirect-uri: http://wl3n3.miit.ru:7003/cabinet/token_auth_callback
        redirect-uri: http://127.0.0.1:7101/CabinetMain-CabinetViewController-context-root/token_auth_callback

#  logging:
#    console:
#      format: plaintext
#      json.pretty: true
#    file:
#      path: "d:\\temp\\esialogs"
#      plaintext.enabled: true
#      json:
#        enabled: true
#        pretty: false

spring:
  datasource:
    url: ${esia.db.url:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=${esia.db.host:db2.miit.ru})(PORT=${esia.db.port:1521})))(CONNECT_DATA=(SERVICE_NAME=${esia.db.name:cgeneral.miit.ru})))}
    username: ${esia.db.username:wlapp_u2_my}
    password: ${esia.db.password}
    driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    ru.unisuite.identity: TRACE
    org.springframework:
      web.client.RestTemplate: DEBUG
